# Generated by Django 4.0.4 on 2022-04-27 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAssinatura', models.CharField(max_length=150)),
                ('valorAssinatura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('fone', models.CharField(max_length=30)),
                ('dataNascimento', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_user)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assinatura')),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=300)),
                ('capa', models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_movie)),
                ('categoriaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filmes')),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios')),
            ],
        ),
    ]
